name: CI
run-name: 'ðŸ¤– [CI] ${{ github.event.pull_request.title }} (${{ github.ref }})'

on:
  pull_request:

jobs:
  ci:
    name: ' ðŸ¤– CI'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'ðŸšš Checkout branch'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'ðŸ“¦ Cache moon artifacts'
        uses: actions/cache@v4
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-moon-

      - name: 'ðŸ“¦ Cache pnpm artifacts'
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 'ðŸŒ‘ Setup moonrepo'
        uses: 'moonrepo/setup-toolchain@v0'

      - name: 'ðŸŒ— CI with moonrepo'
        run: 'moon ci --color'

      - name: 'ðŸŒ• Output retrospect with moonrepo'
        uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
